### ISSUE TITLE
PRODUCT_ID on hdwallet-keepkey-nodehid is possibly incorrect

### ISSUE THREAD

**Issue by cybertito** [shapeshift/hdwallet#444]
Hey, the source defines the USB product id as:

```
export declare const PRODUCT_ID = 1;
```

but my device reports it as 2:

```
> lsusb
...
Bus 001 Device 012: ID 2b24:0002 KeepKey LLC Bitcoin Wallet
...
```

Is this a mistake?

If it isn't, what's the appropriate way to check if a HID device is a KeepKey?

**Comment by cybertito** [comment]
Ok, after looking for a while, I'm guessing that `PRODUCT_ID == 2` is the WebUSB device, while `1` would be the raw USB device. I can't seem to find it though (on Linux, not visible with `lsusb -tv` or in `dmesg`).

I was trying to extend the Frame wallet to support KeepKey, any help appreciated.

**Comment by mrnerdhair** [comment]
In KK firmware v6.0.0 (IIRC!) the USB interface was changed from HID to WebUSB. Because this required a different device descriptor, the product ID was incremented from 1 (the old HID interface) to 2 (the new WebUSB one), since some OSes (cough cough Windows cough) cache device descriptors on device installation and can break when they change.

The `hdwallet-keepkey-nodewebusb` talks to the new interface, while `hdwallet-keepkey-nodehid` talks to the old one, which will only be present on devices which haven't been updated to FW >= 6.0.0, which is why it uses the old product ID.

(Fair warning: `hdwallet-keepkey-nodehid` builds and passes tests and everything, but because it can't actually talk to a modern KK it's not been tested with a real device in a *long* time. YMMV.)

Closing since this particular issue is designed behavior, but we'd be happy to help you support KK on Frame! Drop us a line in the [`#keepkey-general`](https://discord.com/channels/554694662431178782/856626774757736448) channel in our Discord.
