### ISSUE TITLE
Add ability to toggle KeepKey PIN caching

### ISSUE THREAD

**Issue by 0xApotheosis** [shapeshift/hdwallet#489]
Required to meet the requirement specified in the screenshot below:

<img width="286" alt="Screen Shot 2022-03-23 at 6 51 44 pm" src="https://user-images.githubusercontent.com/97164662/159649898-48461cb1-0cfa-40c8-8456-15c158600290.png">

Open question for @pastaghost: is this actually something that can be "enabled", or is the KeepKey functionality just referring to the state of the PIN being cached during a session?

**Comment by 0xApotheosis** [comment]
@pastaghost I have a suspicion this is an invalid requirement, and that we might be conflating with the data in the line below  in [messages.proto](https://github.com/keepkey/device-protocol/blob/a78d09b0ef446578426309f005c016c2b09a2b89/messages.proto#L211) - can you confirm?

```proto
optional bool pin_cached = 16;			// is PIN already cached in session?
```

**Comment by pastaghost** [comment]
@0xApotheosis That's right. Pin caching isn't something that can be "enabled/disabled" selectively - the `pin_cached` parameter in the `Features` protobuf message indicates whether or not the user has recently unlocked the device with a manual PIN entry. In this case, the PIN is cached for the duration of the session so that it doesn't have to be re-entered on each operation.

**Comment by 0xApotheosis** [comment]
This clears everything up, thank you sers.
