### ISSUE TITLE
ATOM support for Ledger

### ISSUE THREAD

**Issue by gomesalexandre** [shapeshift/hdwallet#655]
### Overview

Implements Cosmos support for hdwallet-ledger, similar to the THOR, Ethereum and Bitcoin/UTXOs ones

### References and additional details

https://www.npmjs.com/package/@ledgerhq/hw-app-cosmos

### Acceptance Criteria

- All cosmos base features are supported (sends/derive accounts/get address/??)
- Cosmos Msgs are supported for swaps/native staking (perhaps a stretch and should be done as a follow-up ticket @twblack88 ?)

### Estimated effort

2 days

**Comment by twblack88** [comment]
we're gonna run a poll on twitter. if support overwhelming then we can turbo this guy in. Would be cool to explore the native staking and messages since it;s been a minute and we can spec it out. 

Our theme for cosmos isn't until q3 but if we have things specced then we can slot them in there depending on bandwith. I'm keen to learn for sure.
